### ISSUE TITLE
TODO before release 0.1

### ISSUE THREAD

**Issue by Jamesits** [Jamesits/NoWebview#1]
* [ ] Remove artifacts from copy & paste code
 * [ ] Testing against various apps
 * [ ] Browser compatibility test
 * [ ] Multi levels of warning display: {full page, bottom bar} * {closable, unclosable}
 * [ ] Re-design warning page
 * [ ] Rewrite warning information
 * [ ] A website
 	* [ ] To end user: Why Webview is eval
 	* [ ] To website dev: How to integrate this script to your own project
 	* [ ] To application dev: How to replace webview with chrome custom tab or wkwebview

**Comment by ShadowRZ** [comment]
@Jamesits 
(Maybe) One of the reasons: https://citizenlab.org/2016/11/wechat-china-censorship-one-app-two-systems/
